# Generated by Django 5.0.6 on 2024-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_upload_video_subfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_video',
            name='subfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
